# Generated by Django 2.1.7 on 2019-03-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'permissions': (('edit_answer', 'Can edit answer'), ('read_answer', 'Can read answer')),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('exclusive_answer', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'permissions': (('edit_question', 'Can edit question'), ('read_question', 'Can read question')),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'tests',
                'permissions': (('edit_test', 'Can edit test'), ('read_test', 'Can read test')),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ManyToManyField(to='MCQAssignmentsApp.Test'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCQAssignmentsApp.Question'),
        ),
    ]
