# Generated by Django 2.1.7 on 2019-03-16 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MCQAssignmentsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCQAssignmentsApp.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCQAssignmentsApp.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCQAssignmentsApp.Test')),
            ],
            options={
                'verbose_name': 'student answer',
                'verbose_name_plural': 'student answers',
            },
        ),
    ]
