# Generated by Django 2.1.7 on 2019-04-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQAssignmentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuserassignment',
            name='assignment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
