# Generated by Django 2.1.5 on 2019-02-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQAssignmentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exclusive_answer',
            field=models.BooleanField(default=True),
        ),
    ]
