# Generated by Django 2.1.7 on 2019-04-18 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MCQAssignmentsApp', '0002_testuserassignment_assignment_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'unlocked_video',
                'verbose_name_plural': 'unlocked_videos',
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='unlockedvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCQAssignmentsApp.YouTubeVideo'),
        ),
        migrations.AlterUniqueTogether(
            name='unlockedvideo',
            unique_together={('student', 'video')},
        ),
    ]
